# Generated by Django 2.2.2 on 2019-08-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pluses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
