# Generated by Django 2.2.2 on 2019-08-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='num_of_choices',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
