# Generated by Django 2.2.2 on 2019-08-03 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_choices_full_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='full_votes',
        ),
    ]
