# Generated by Django 2.2.2 on 2019-08-03 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_choices_full_votes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'permissions': (('can_vote_poll', 'can_vote_poll'),)},
        ),
    ]
