# Generated by Django 2.2.2 on 2019-08-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_poll_total_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='total_votes',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
